# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
create_project -in_memory -part xc7a75tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir D:/study/COD/lab/lab5/lab5/lab5.cache/wt [current_project]
set_property parent.project_path D:/study/COD/lab/lab5/lab5/lab5.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
add_files D:/study/COD/lab/lab5/lab5/lab5.srcs/sources_1/data_ip.coe
add_files D:/study/COD/lab/lab5/lab5/lab5.srcs/sources_1/ip/ins_ip.coe
add_files -quiet d:/study/COD/lab/lab5/lab5/lab5.srcs/sources_1/ip/data_mem/data_mem.dcp
set_property used_in_implementation false [get_files d:/study/COD/lab/lab5/lab5/lab5.srcs/sources_1/ip/data_mem/data_mem.dcp]
add_files -quiet d:/study/COD/lab/lab5/lab5/lab5.srcs/sources_1/ip/ins_mem/ins_mem.dcp
set_property used_in_implementation false [get_files d:/study/COD/lab/lab5/lab5/lab5.srcs/sources_1/ip/ins_mem/ins_mem.dcp]
read_verilog -library xil_defaultlib {
  D:/study/COD/lab/lab5/lab5/lab5.srcs/sources_1/new/control.v
  D:/study/COD/lab/lab5/lab5/lab5.srcs/sources_1/new/REG_FILE.v
  D:/study/COD/lab/lab5/lab5/lab5.srcs/sources_1/new/alu.v
  D:/study/COD/lab/lab5/lab5/lab5.srcs/sources_1/new/top.v
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}

synth_design -top top -part xc7a75tcsg324-1


write_checkpoint -force -noxdef top.dcp

catch { report_utilization -file top_utilization_synth.rpt -pb top_utilization_synth.pb }
